### ISSUE TITLE
Deep graph infomax

### ISSUE THREAD

**Issue by inhail** [inhail/Graph-Neural-Network#5]
我們用loss來update encoder的參數而已嗎? discriminator需不需要update?
如果需要，要怎麼同時update encoder and discriminator?
如果不需要，要怎麼保證train出來的品質?

**Comment by sophialien** [comment]
> 我們用loss來update encoder的參數而已嗎? discriminator需不需要update?
> 如果需要，要怎麼同時update encoder and discriminator?
> 如果不需要，要怎麼保證train出來的品質?



都要根據下式更新
![IMG_6371](https://user-images.githubusercontent.com/52566175/74646555-11ee9400-51b5-11ea-997f-1be40d4f4e1e.jpeg)

另, 此理論根據是1983年 DV證明的MI下界：
![IMG_6370](https://user-images.githubusercontent.com/52566175/74646716-524e1200-51b5-11ea-9587-d851d776fc57.jpeg)

這也就是DIM文中引出discriminator之依據
